# Generated by Django 2.2.5 on 2020-03-15 07:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('registred_number', models.CharField(default=1, max_length=50, null=True)),
                ('user', models.CharField(default=1, max_length=50)),
                ('q1', models.BooleanField(blank=True, default=False)),
                ('q2', models.BooleanField(blank=True, default=False)),
                ('q3', models.BooleanField(blank=True, default=False)),
                ('q4', models.BooleanField(blank=True, default=False)),
                ('q5', models.BooleanField(blank=True, default=False)),
                ('q6', models.BooleanField(blank=True, default=False)),
                ('q7', models.BooleanField(blank=True, default=False)),
                ('q8', models.BooleanField(blank=True, default=False)),
                ('q9', models.BooleanField(blank=True, default=False)),
                ('q10', models.BooleanField(blank=True, default=False)),
                ('q11', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('q12', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='None', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registred_number', models.TextField(max_length=30)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.VehicleType')),
            ],
        ),
    ]
