# Generated by Django 2.2.5 on 2020-03-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='name',
        ),
    ]
