# Generated by Django 2.2.5 on 2020-03-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_remove_vehicletype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
