# Generated by Django 3.0.4 on 2020-03-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_auto_20200323_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='q12',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
